/**
 * DIE LUECKENSAETZE — drei je Lerneinheit.
 *
 * `%` ist die Luecke. Der Satz steht auf dem Bildschirm und wird
 * vorgelesen, das Zielwort mit; geschrieben wird nur das eine Wort.
 *
 * VIER REGELN, an die sich jeder Satz haelt - und das Tor `deutsch`
 * prueft alle vier, nicht nur diese Zeile:
 *
 *   1. Hoechstens neun Woerter. Ein laengerer Satz misst Lesen statt
 *      Schreiben, und auf 844 x 390 bricht er in eine dritte Zeile.
 *   2. Das Zielwort steht NIE am Satzanfang. Sonst verriete der
 *      Satzanfang die Grossschreibung - und Gross/klein ist hier ein
 *      eigener Fehler mit eigener Meldung.
 *   3. Kein zweites Lernwort DESSELBEN Phaenomens im Satz. Sonst uebt
 *      der Satz zwei Dinge auf einmal, und welches davon schiefging,
 *      sagt er nicht.
 *   4. Nur Woerter aus Leas Welt: Schule, Familie, Tiere, draussen.
 *
 * DREI und nicht einer: ein Wort sitzt nach dreimal richtig an drei
 * Tagen. Stuende es dreimal im selben Satz, waere beim dritten Mal der
 * Satz gelernt und nicht das Wort.
 */
export const SAETZE = {
  /* --- Silben trennen ------------------------------------------------- */
  Boden:['Der Ball liegt auf dem %.','Mein Stift ist auf den % gefallen.','Im Keller ist der % sehr kalt.'],
  Ding:['Was ist das für ein %?','Ein solches % habe ich nie gesehen.','Dieses kleine % gehört meiner Schwester.'],
  etwas:['Ich möchte dir % zeigen.','Hast du % dagegen?','Da liegt % unter dem Bett.'],
  Finger:['Mein kleiner % tut weh.','Sie zeigt mit dem % auf das Bild.','Am % trägt sie einen Ring.'],
  Fisch:['Im Teich schwimmt ein großer %.','Der % hat rote Flossen.','Mein Onkel hat einen % gefangen.'],
  Flasche:['Die % steht im Kühlschrank.','Gib mir bitte die %.','Aus der % läuft Wasser.'],
  gegen:['Wir spielen morgen % die andere Klasse.','Der Ball fliegt % die Wand.','Hast du Medizin % Husten?'],
  'gehören':['Diese Schuhe % meiner Schwester.','Wem % die Stifte auf dem Tisch?','Die Bücher % in das Regal.'],
  genau:['Sie weiß %, wo der Schlüssel liegt.','Das ist % die richtige Farbe.','Lies die Aufgabe % durch.'],
  gerade:['Er kommt % nach Hause.','Die Linie ist ganz %.','Ich habe % keine Zeit.'],
  Geschichte:['Am Abend liest Mama eine %.','Diese % kenne ich schon.','Er erzählt eine lustige %.'],
  Gesicht:['Ihr % ist ganz rot.','Wasch dir bitte das %.','Im Spiegel sehe ich mein %.'],
  gleich:['Wir sind beide % groß.','Ich komme sofort %.','Die beiden Bilder sehen % aus.'],
  Hals:['Mein % tut seit gestern weh.','Um den % trägt sie eine Kette.','Der Schwan hat einen langen %.'],
  helfen:['Kannst du mir bitte %?','Wir % beim Aufräumen.','Die Großen % den Kleinen.'],
  heute:['Wir gehen % ins Schwimmbad.','Es regnet % den ganzen Tag.','Hast du % schon geübt?'],
  lachen:['Alle mussten laut %.','Wir % über den Witz.','Sie kann herzlich %.'],
  Licht:['Mach bitte das % an.','Im Zimmer brennt kein %.','Das % der Lampe ist warm.'],
  Loch:['In der Hose ist ein %.','Der Hund gräbt ein tiefes %.','Durch das % pfeift der Wind.'],
  Luft:['Die % ist hier frisch.','Im Ballon ist warme %.','Wir brauchen frische % im Zimmer.'],
  machen:['Was sollen wir jetzt %?','Wir % zusammen Hausaufgaben.','Sie % einen Ausflug an den See.'],
  Mensch:['Kein % war auf der Straße.','Jeder % braucht Schlaf.','Ein alter % sitzt auf der Bank.'],
  Milch:['Im Glas ist noch %.','Die Katze trinkt gern %.','Wir holen % vom Bauern.'],
  Nase:['Meine % ist kalt.','Der Hund hat eine feuchte %.','Halte dir die % zu.'],
  neben:['Mein Platz ist % dem Fenster.','Sie sitzt % ihrer Freundin.','Stell den Stuhl % den Tisch.'],
  neu:['Mein Fahrrad ist ganz %.','Das Heft sieht noch % aus.','Alles hier ist für mich %.'],
  oben:['Das Buch liegt ganz %.','Von % sieht alles klein aus.','Wir wohnen % im dritten Stock.'],
  reich:['Der König war sehr %.','Man muss nicht % sein.','Dieses Land ist % an Wäldern.'],
  reiten:['Am Samstag darf sie %.','Wir lernen % auf dem Hof.','Er kann schon gut %.'],
  Sache:['Das ist eine schwierige %.','Diese % geht dich nichts an.','Eine solche % passiert selten.'],
  schenken:['Wir % Oma eine Blume.','Was soll ich ihm %?','Zum Geburtstag % wir ihr ein Buch.'],
  schlecht:['Mir ist seit gestern %.','Das Wetter wird morgen %.','Sie hat % geschlafen.'],
  Seite:['Schlag bitte die nächste % auf.','Auf dieser % steht ein Gedicht.','Er stellt sich an meine %.'],
  sprechen:['Wir % leise im Unterricht.','Kannst du lauter %?','Sie will mit dir %.'],
  springen:['Die Kinder % über die Pfütze.','Wir % vom Rand ins Wasser.','Der Frosch kann weit %.'],
  Stein:['Ein großer % liegt am Weg.','Sie legt den % auf den Tisch.','Der % ist glatt und rund.'],
  tanken:['Wir müssen unterwegs noch %.','Papa hält an der Säule zum %.','Bevor wir losfahren, müssen wir %.'],
  Tasche:['Meine % ist sehr schwer.','In der % steckt mein Schlüssel.','Pack das Heft in die %.'],
  Wagen:['Der rote % steht vor dem Haus.','Wir schieben den % den Berg hinauf.','Im % sitzen vier Leute.'],
  weinen:['Das Baby fängt an zu %.','Sie musste vor Freude %.','Warum % die Kleinen?'],
  Woche:['Nächste % fahren wir weg.','Die % hat sieben Tage.','In einer % habe ich Geburtstag.'],
  Zeitung:['Papa liest jeden Tag die %.','In der % steht ein Bild.','Er holt die % aus dem Briefkasten.'],

  /* --- r nach dem Selbstlaut ------------------------------------------ */
  Arm:['Mein linker % tut weh.','Sie nimmt das Kind auf den %.','Am % hat er ein Pflaster.'],
  Dorf:['Wir wohnen in einem kleinen %.','Im % gibt es einen Bäcker.','Das % liegt hinter dem Wald.'],
  dort:['Stell den Korb bitte % hin.','Siehst du das Haus %?','Wir treffen uns %.'],
  Eltern:['Meine % sind heute zu Hause.','Die % warten vor der Schule.','Ich frage meine % danach.'],
  Erde:['Der Wurm lebt in der %.','Die % dreht sich um die Sonne.','Er gräbt ein Loch in die %.'],
  erst:['Wir essen % und spielen dann.','Ich muss % die Aufgaben machen.','Sie kommt % um acht Uhr.'],
  gern:['Ich esse % Nudeln.','Sie singt sehr %.','Kommst du % mit uns?'],
  gestern:['Wir waren % im Schwimmbad.','Hat es % geregnet?','Sie hat % Geburtstag gehabt.'],
  kurz:['Meine Haare sind ganz %.','Der Weg ist zum Glück %.','Warte bitte ganz %.'],
  merken:['Ich kann mir das gut %.','Du sollst dir die Zahl %.','Wir % uns den Weg.'],
  morgen:['Wir fahren % zu Oma.','Hast du % Zeit?','Die Schule beginnt % später.'],
  schwer:['Die Tasche ist zu %.','Diese Aufgabe war sehr %.','Der Koffer ist ziemlich %.'],
  sofort:['Komm bitte % her.','Sie war % wieder da.','Das musst du % melden.'],
  stark:['Mein Bruder ist sehr %.','Der Wind weht heute %.','Diese Brille ist zu %.'],
  'Tür':['Mach bitte die % zu.','Vor der % steht ein Paket.','Die % klemmt ein wenig.'],
  werfen:['Wir % den Ball über den Zaun.','Kannst du so weit %?','Sie % Steine ins Wasser.'],
  Wurst:['Auf dem Brot liegt %.','Der Hund bettelt um die %.','Ich mag diese % nicht.'],

  /* --- Wörter mit ie --------------------------------------------------- */
  Beispiel:['Nenne mir bitte ein %.','Das ist ein gutes %.','Sie erklärt es an einem %.'],
  Brief:['Oma hat mir einen % geschickt.','Im Kasten liegt ein %.','Ich schreibe dir einen %.'],
  Briefe:['Sie sammelt alte %.','Im Kasten liegen zwei %.','Wir werfen die % ein.'],
  geschrieben:['Das hast du falsch %.','Der Text ist schön %.','Wer hat das an die Tafel %?'],
  lesen:['Wir % jeden Abend ein Buch.','Möchtest du das laut %?','Die Kinder % in der Pause.'],
  liest:['Mama % uns eine Geschichte vor.','Wer % heute den Text?','Er % schon ganz schnell.'],
  nie:['So etwas habe ich % gesehen.','Ich war % in Italien.','Das vergesse ich %.'],
  niemals:['Das mache ich %!','Er würde uns % anlügen.','So etwas darf % passieren.'],
  riechen:['Die Blumen % sehr gut.','Kannst du den Kuchen %?','Hier % die Socken schlecht.'],
  riecht:['Der Kuchen % herrlich.','Es % nach Regen.','Meine Jacke % nach Rauch.'],
  schieben:['Wir % den Schrank zur Seite.','Kannst du mir helfen zu %?','Sie % das Rad den Berg hoch.'],
  schiebt:['Er % den Wagen vor sich her.','Papa % den Tisch nach hinten.','Sie % die Tür langsam auf.'],
  schwierig:['Diese Aufgabe war sehr %.','Das Wort ist % zu schreiben.','Es war %, ihn zu finden.'],
  tief:['Der See ist sehr %.','Grab das Loch nicht so %.','Sie holt % Luft.'],
  tiefer:['Das Wasser wird immer %.','Hier ist der Schnee %.','Der Graben ist % als gedacht.'],
  Tier:['Im Wald lebt ein scheues %.','Welches % magst du am liebsten?','Ein kleines % huscht vorbei.'],
  Tiere:['Im Zoo gibt es viele %.','Die % schlafen im Stall.','Wir füttern die % im Winter.'],
  verlieren:['Wir dürfen das Spiel nicht %.','Pass auf, nichts zu %.','Sie % selten die Geduld.'],
  ziehen:['Wir % den Schlitten den Hang hoch.','Die Pferde % den Wagen.','Kannst du fester %?'],
  zieht:['Der Hund % an der Leine.','Es % hier fürchterlich.','Sie % den Mantel an.'],
  zielen:['Du musst genau %.','Wir % auf die Dose.','Beim Wurf muss man %.'],
  zielt:['Er % auf den Korb.','Sie % mit dem Ball.','Der Pfeil % nach oben.'],
  Zwiebel:['Mama schneidet eine %.','Von der % muss ich weinen.','In der Suppe ist eine %.'],

  /* --- Doppelte Mitlaute ----------------------------------------------- */
  dumm:['Diese Frage ist nicht %.','Der Hund ist gar nicht %.','So ein Fehler ist einfach %.'],
  essen:['Wir % heute Nudeln.','Was möchtest du %?','Die Kinder % in der Küche.'],
  kommen:['Wann % deine Eltern?','Wir % gleich nach Hause.','Die Gäste % um sechs.'],
  schlimm:['Die Wunde ist nicht %.','Das Wetter war richtig %.','So % war es gar nicht.'],
  schwimmen:['Die Enten % auf dem Teich.','Wir gehen morgen %.','Kannst du schon %?'],
  schnell:['Der Hase läuft sehr %.','Mach bitte ein bisschen %.','Das ging aber %!'],
  stellen:['Wir % die Blumen ans Fenster.','Kannst du den Stuhl dorthin %?','Sie % den Korb auf den Tisch.'],
  vergessen:['Ich habe mein Heft %.','Das darfst du nicht %.','Wir haben die Zeit %.'],
  Zimmer:['Mein % ist sehr hell.','Im % steht ein Bett.','Räum bitte dein % auf.'],
  zusammen:['Wir spielen gern %.','Die Klasse singt %.','Alles % kostet zehn Euro.'],

  /* --- Wörter mit tz ---------------------------------------------------- */
  Platz:['Mein % ist am Fenster.','Auf dem % spielen Kinder.','Ist hier noch ein % frei?'],
  'Pfütze':['In der % steht Regenwasser.','Der Hund springt durch die %.','Vor der Tür ist eine %.'],
  'plötzlich':['Es wurde % ganz dunkel.','Der Hund bellte %.','Sie blieb % stehen.'],
  'schützen':['Der Helm soll dich %.','Bäume % vor der Sonne.','Wir müssen die Tiere %.'],

  /* --- Wörter mit ck ---------------------------------------------------- */
  'Glück':['Du hast großes % gehabt.','Zum % hat es nicht geregnet.','Wir wünschen dir viel %.'],
  'glücklich':['Sie war sehr % darüber.','Der Hund sieht % aus.','Wir sind heute richtig %.'],
  Schreck:['Der % saß ihm in den Gliedern.','Vor % ließ sie das Glas fallen.','Das war ein großer %.'],
  erschrecken:['Du darfst die Katze nicht %.','Lass dich davon nicht %.','Die Kinder % sich im Dunkeln.'],
  'Stück':['Möchtest du noch ein % Kuchen?','Ein % Seife liegt im Bad.','Sie isst nur ein kleines %.'],
  verstecken:['Wir % uns hinter dem Baum.','Wo soll ich mich %?','Du kannst dich hier %.'],
  'zurück':['Wir fahren morgen wieder %.','Gib mir bitte mein Buch %.','Sie kommt gleich %.'],

  /* --- Das h zwischen den Silben ---------------------------------------- */
  'blühen':['Im Garten % die Rosen.','Die Bäume % im Frühling.','Bald % die Tulpen.'],
  drehen:['Wir % uns im Kreis.','Kannst du den Schlüssel %?','Die Räder % sich schnell.'],
  gehen:['Wir % jeden Tag zur Schule.','Möchtest du mit uns %?','Die Kinder % nach Hause.'],
  Kuh:['Auf der Wiese steht eine %.','Die % gibt uns Milch.','Eine braune % frisst Gras.'],
  'Kühe':['Auf der Weide sind viele %.','Die % kommen in den Stall.','Der Bauer melkt die %.'],
  Schuh:['Mein linker % drückt.','Im % ist ein Stein.','Er bindet seinen % zu.'],
  Schuhe:['Meine neuen % sind rot.','Zieh bitte deine % aus.','Die % liegen im Flur.'],
  sehen:['Wir % uns morgen wieder.','Kannst du das Schild %?','Die Kinder % einen Film.'],
  'stehen':['Wir % vor der Schule.','Die Gläser % im Schrank.','Dort % zwei Fahrräder.'],
  Zeh:['Mein kleiner % tut weh.','Am % habe ich ein Pflaster.','Sie stößt sich den %.'],
  'Zehen':['Meine % sind ganz kalt.','Er wackelt mit den %.','Im Sand spürt man die %.'],

  /* --- Verlängern hilft -------------------------------------------------- */
  Abend:['Am % lesen wir ein Buch.','Der % war sehr schön.','Wir wünschen euch einen schönen %.'],
  Abende:['Die % sind jetzt kühl.','Im Sommer sind die % lang.','Zwei % hat sie geübt.'],
  abends:['Wir putzen % die Zähne.','Sie liest % im Bett.','Der Hund bellt % oft.'],
  Berg:['Wir wandern auf den %.','Der % ist mit Schnee bedeckt.','Hinter dem % geht die Sonne unter.'],
  Berge:['Im Urlaub sehen wir die %.','Die % sind sehr hoch.','Wir fahren gern in die %.'],
  erlauben:['Meine Eltern % mir das nicht.','Kannst du uns das %?','Sie % ihm ein Eis.'],
  erlaubt:['Hier ist Fahrradfahren nicht %.','Mama hat es mir %.','Das ist leider nicht %.'],
  fremd:['Der Mann war mir ganz %.','Hier ist alles neu und %.','Diese Stadt ist mir %.'],
  fremder:['Ein % Hund lief über die Straße.','Vor uns stand ein % Mann.','Ein % Junge fragte nach dem Weg.'],
  Geld:['Ich habe kein % dabei.','Das % steckt in der Tasche.','Für das % kaufen wir Brot.'],
  Gelder:['Die gesammelten % gehen an den Zoo.','Alle % kommen der Schule zugute.','Die % reichen für neue Bücher.'],
  lieben:['Wir % unsere Großeltern.','Die Kinder % ihren Hund.','Alle % diesen Kuchen.'],
  liebt:['Sie % ihre kleine Schwester.','Der Hund % es zu rennen.','Oma % Blumen im Garten.'],
  liegen:['Die Bücher % auf dem Tisch.','Wir % im Gras.','Die Schlüssel % im Flur.'],
  liegt:['Das Heft % unter dem Bett.','Der Ball % im Garten.','Sie % noch im Bett.'],
  rund:['Der Tisch ist ganz %.','Ein Ball ist immer %.','Die Scheibe ist % und flach.'],
  runder:['Dieser Teller ist % als jener.','Ein % Stein lag am Weg.','Der Mond sieht jeden Tag % aus.'],
  steigen:['Wir % in den Zug.','Die Preise % jedes Jahr.','Kannst du auf die Leiter %?'],
  steigt:['Sie % auf den Baum.','Der Rauch % nach oben.','Er % aus dem Auto.'],
  werden:['Wir % bald größer.','Die Tage % wieder länger.','Was möchtest du einmal %?'],
  wird:['Es % langsam dunkel.','Sie % morgen acht Jahre alt.','Das Wetter % wieder besser.'],

  /* --- Von a zu ä --------------------------------------------------------- */
  alt:['Mein Fahrrad ist schon sehr %.','Wie % bist du?','Der Baum ist hundert Jahre %.'],
  'älter':['Meine Schwester ist % als ich.','Er sieht % aus.','Jedes Jahr werden wir %.'],
  Ast:['Auf dem % sitzt ein Vogel.','Ein dicker % ist abgebrochen.','Der Hund trägt einen % im Maul.'],
  'Äste':['Die % biegen sich im Wind.','Im Winter sind die % kahl.','Wir sammeln % für das Feuer.'],
  lang:['Der Weg ist sehr %.','Ihre Haare sind ganz %.','Wie % dauert die Pause?'],
  'länger':['Der Winter dauert % als gedacht.','Dieses Seil ist % als jenes.','Bleib bitte noch etwas %.'],
  laufen:['Wir % zur Schule.','Die Kinder % über die Wiese.','Kannst du schneller %?'],
  'läuft':['Der Hund % über den Hof.','Das Wasser % aus dem Hahn.','Sie % jeden Morgen.'],
  Nacht:['In der % ist es still.','Die % war sehr kalt.','Wir wünschen dir eine gute %.'],
  'Nächte':['Die % werden immer kürzer.','Drei % blieben wir im Zelt.','Im Sommer sind die % warm.'],
  Saft:['Im Glas ist roter %.','Möchtest du noch etwas %?','Der % schmeckt nach Apfel.'],
  'Säfte':['Im Kühlschrank stehen zwei %.','Diese % sind sehr süß.','Wir kaufen % für das Fest.'],

  /* --- Kleine Wörter im Satz ---------------------------------------------
   * Satzregel 3 gilt hier nur innerhalb derselben Wortfamilie. „dem", „ein",
   * „in", „zu" sind das Bindegewebe jedes deutschen Satzes; ein Satz
   * ohne sie ist keiner. Verwirrend waere allein die zweite Form
   * DESSELBEN Eintrags - stuende „dem" im Satz zu „den", muesste Lea
   * raten, welche Luecke gemeint ist. Das bleibt verboten, und das Tor
   * setzt es durch. */
  am:['Wir treffen uns % Bahnhof.','Sie sitzt % Tisch und malt.','Wir haben % Sonntag frei.'],
  an:['Das Bild hängt % der Wand.','Wir denken oft % dich.','Sie klopft % die Tür.'],
  dein:['Wo ist % Heft?','Ist das % Fahrrad?','Hier liegt % Schlüssel.'],
  deinem:['Das Buch liegt auf % Tisch.','Wir fahren mit % Rad.','Sie steht vor % Zimmer.'],
  deinen:['Hast du % Ranzen gepackt?','Ich sehe % Bruder dort.','Gib mir bitte % Stift.'],
  dem:['Der Ball liegt unter % Bett.','Sie sitzt auf % Stuhl.','Mit % Bus fahren wir heim.'],
  den:['Wir füttern % Hund.','Sie öffnet % Schrank.','Hast du % Brief gelesen?'],
  dies:['Alles % gehört mir.','Was soll % bedeuten?','Nimm % bitte mit.'],
  diesem:['In % Haus wohnt meine Oma.','Mit % Stift schreibe ich gern.','Aus % Grund bleiben wir hier.'],
  diesen:['Kennst du % Jungen?','Wir nehmen % Weg.','Ich mag % Kuchen sehr.'],
  ein:['Dort steht % Baum.','Sie hat % Pferd gemalt.','Wir brauchen noch % Glas.'],
  einem:['Wir wohnen in % Dorf.','Sie kommt aus % anderen Land.','Mit % Lächeln sagt er ja.'],
  einen:['Ich habe % Bruder.','Sie malt % Vogel.','Wir pflanzen % Baum.'],
  euer:['Wo ist % Ball?','Ist das % Haus?','Hier liegt % Heft.'],
  eurem:['Wir waren in % Garten.','Mit % Auto fahrt ihr schnell.','Vor % Haus steht ein Baum.'],
  euren:['Habt ihr % Hund dabei?','Ich sehe % Lehrer dort.','Zeigt mir bitte % Plan.'],
  ganz:['Der Teller ist wieder %.','Sie hat % recht.','Das Glas blieb %.'],
  ganzem:['Von % Herzen danke ich dir.','Mit % Mut sprang er hinein.','Aus % Wald kam ein Rauschen.'],
  ganzen:['Wir haben den % Tag gespielt.','Sie aß den % Kuchen auf.','Im % Haus war es still.'],
  ihm:['Ich gebe % das Buch.','Wir helfen % gern.','Sag % bitte Bescheid.'],
  ihn:['Wir haben % gestern gesehen.','Kennst du % gut?','Ich rufe % später an.'],
  ihnen:['Wir danken % herzlich.','Hilf % bitte beim Tragen.','Ich habe % geschrieben.'],
  ihr:['Wo ist % Ball geblieben?','Das ist % Fahrrad.','Hier liegt % Mantel.'],
  ihre:['Sie sucht % Brille.','Wo sind % Schuhe?','Das war % Idee.'],
  ihrem:['Sie spielt mit % Bruder.','In % Zimmer ist es warm.','Mit % Rad fährt sie schnell.'],
  ihren:['Sie ruft % Hund.','Hast du % Bruder gesehen?','Gib % Eltern das Heft.'],
  im:['Wir spielen % Garten.','Das Buch liegt % Regal.','Sie schläft % Zelt.'],
  in:['Wir gehen % die Schule.','Leg das Heft % die Tasche.','Sie springt % das Wasser.'],
  jede:['Sie gießt % Pflanze.','Fast % Aufgabe war leicht.','Bei uns hilft % Hand.'],
  jedem:['Wir geben % Kind ein Eis.','Bei % Wetter gehen wir raus.','Aus % Fenster schaut jemand.'],
  jeden:['Wir üben % Tag.','Sie grüßt % Nachbarn.','Ich sehe % Morgen die Sonne.'],
  kein:['Hier ist % Platz frei.','Es war % Mensch da.','Ich habe % Geld dabei.'],
  keinem:['Mit % Wort hat sie geantwortet.','Aus % Fenster kam Licht.','Bei % anderen wäre das passiert.'],
  keinen:['Ich habe % Hunger.','Sie hat % Bruder.','Wir finden % Weg hinaus.'],
  mein:['Hier liegt % Heft.','Wo ist % Ball?','Das ist % Platz.'],
  meinem:['In % Zimmer ist es hell.','Ich spiele mit % Bruder.','Auf % Tisch liegt ein Buch.'],
  meinen:['Kennst du % Hund?','Ich suche % Schlüssel.','Sie hat % Namen vergessen.'],
  mich:['Er ruft % beim Namen.','Kannst du % hören?','Das freut % sehr.'],
  mir:['Gib % bitte das Buch.','Hilfst du % dabei?','Es geht % gut.'],
  sein:['Wo ist % Ball geblieben?','Das ist % Fahrrad.','Dort steht % Vater.'],
  seinem:['Er spielt mit % Hund.','In % Zimmer ist alles ordentlich.','Auf % Teller liegt Brot.'],
  seinen:['Er sucht % Schlüssel.','Kennst du % Bruder?','Sie mag % Hund sehr.'],
  seit:['Wir warten % einer Stunde.','Sie ist % gestern krank.','Es regnet % heute Morgen.'],
  uns:['Besuch % doch morgen.','Er hilft % beim Umzug.','Wir freuen % sehr.'],
  unserem:['In % Garten blüht viel.','Mit % Auto fahren wir weg.','Vor % Haus steht ein Baum.'],
  unseren:['Wir füttern % Hund.','Kennst du % Lehrer?','Sie mag % Garten.'],
  vom:['Der Apfel fällt % Baum.','Wir kommen gerade % Markt.','Sie springt % Stuhl.'],
  von:['Das Buch ist % Oma.','Wir sprechen % dir.','Sie kommt % weit her.'],
  welche:['Sag mir, % Farbe du magst.','Weißt du, % Blume das ist?','Rate, % Hand etwas hält.'],
  welchem:['Auf % Platz sitzt du?','In % Haus wohnt sie?','Mit % Bus fahrt ihr?'],
  welchen:['Rate, % Weg wir nehmen.','Sag mir, % Kuchen du magst.','Weißt du, % Hund sie meint?'],
  wem:['Sag mir, % das gehört.','Mit % spielst du?','Von % hast du das?'],
  wen:['Sag mir, % du meinst.','Für % ist das Geschenk?','Über % habt ihr gelacht?'],
  zu:['Wir gehen % Oma.','Das ist % laut.','Komm bitte % mir.'],
  zum:['Wir fahren % Bahnhof.','Sie geht % Arzt.','Es ist Zeit % Essen.'],
  zur:['Wir gehen % Schule.','Sie fährt % Arbeit.','Es ist Zeit % Pause.'],

  /* --- Umlaut und Verlängern ---------------------------------------------- */
  Arzt:['Wir gehen morgen zum %.','Der % hört mein Herz ab.','Beim % war ich gestern.'],
  'Ärzte':['Im Krankenhaus arbeiten viele %.','Die % helfen den Kranken.','Zwei % sprechen miteinander.'],
  backen:['Wir % heute einen Kuchen.','Oma kann sehr gut %.','Möchtest du Plätzchen %?'],
  'Bäcker':['Der % steht früh auf.','Wir holen Brot beim %.','Mein Onkel ist %.'],
  Band:['Im Haar trägt sie ein %.','Das % ist rot und lang.','Binde das % zu einer Schleife.'],
  'Bänder':['Die bunten % flattern im Wind.','Sie kauft zwei % im Laden.','An dem Geschenk hängen %.'],
  Hand:['Gib mir bitte deine %.','Die % tut mir weh.','Er hebt die % zum Gruß.'],
  'Hände':['Wasch dir die % vor dem Essen.','Meine % sind ganz kalt.','Sie klatscht in die %.'],
  kaufen:['Wir % Brot und Milch.','Möchtest du dir ein Eis %?','Sie % einen neuen Schrank.'],
  'Verkäufer':['Der % ist sehr freundlich.','Wir fragen den % nach dem Preis.','Ein % räumt das Regal ein.'],
  Land:['Wir fahren aufs %.','Dieses % liegt in Europa.','Vom Schiff sehen wir %.'],
  'Länder':['In Europa gibt es viele %.','Diese % liegen am Meer.','Wir malen die % bunt an.'],
  lassen:['Wir % den Hund im Garten.','Kannst du das bitte %?','Sie % die Tür offen.'],
  'lässt':['Er % mich nicht vorbei.','Sie % den Drachen steigen.','Mama % uns draußen spielen.'],
  Mann:['Ein alter % sitzt auf der Bank.','Der % trägt einen Hut.','Dort drüben wartet ein %.'],
  'Männer':['Zwei % tragen den Schrank.','Die % arbeiten im Garten.','Drei % stehen vor dem Haus.'],
  Rad:['Mein % steht im Keller.','Am % fehlt die Klingel.','Sie fährt mit dem % zur Schule.'],
  'Räder':['Die % drehen sich schnell.','Unsere % stehen im Schuppen.','Das Auto hat vier %.'],
  'stärker':['Mein Bruder ist % als ich.','Der Wind wird immer %.','Dieser Kleber hält %.'],
  Wald:['Im % singen die Vögel.','Wir gehen in den %.','Hinter dem % liegt ein See.'],
  'Wälder':['Die % sind im Herbst bunt.','In Bayern gibt es viele %.','Durch die % führt ein Weg.'],

  /* --- Gestern war es so --------------------------------------------------- */
  bleiben:['Wir % heute zu Hause.','Möchtest du noch etwas %?','Die Kinder % im Zelt.'],
  blieben:['Wir % gestern zu Hause.','Alle % ganz ruhig.','Sie % eine Woche am Meer.'],
  'aßen':['Wir % gestern Nudeln.','Die Kinder % ihren Nachtisch auf.','Alle % gemeinsam am Tisch.'],
  fallen:['Die Blätter % von den Bäumen.','Pass auf, nicht zu %!','Im Winter % Flocken vom Himmel.'],
  fielen:['Gestern % viele Blätter herab.','Die Äpfel % ins Gras.','Zwei Bücher % vom Regal.'],
  geben:['Wir % dir das Heft.','Kannst du mir bitte Wasser %?','Die Kühe % viel Milch.'],
  gaben:['Wir % ihr ein Geschenk.','Die Eltern % uns Geld.','Alle % ihr Bestes.'],
  gingen:['Wir % gestern ins Kino.','Die Kinder % nach Hause.','Alle % über die Brücke.'],
  halten:['Wir % die Tür auf.','Kannst du das kurz %?','Die Busse % an der Ecke.'],
  hielten:['Wir % die Fahne hoch.','Alle % kurz inne.','Die Züge % im Bahnhof.'],
  'hießen':['Die beiden Hunde % Rex und Bello.','Früher % wir anders.','Wie % eure Nachbarn?'],
  kamen:['Gestern % viele Gäste.','Wir % zu spät.','Die Vögel % aus dem Süden.'],
  'können':['Wir % das schon gut.','Kinder % viel lernen.','Sie % morgen mitkommen.'],
  konnten:['Wir % gestern nicht kommen.','Alle % die Aufgabe lösen.','Die Kleinen % noch nicht laufen.'],
  'ließen':['Wir % das Fenster offen.','Sie % den Drachen steigen.','Die Eltern % uns spielen.'],
  liefen:['Wir % über die Wiese.','Alle % um die Wette.','Die Kinder % zum Bus.'],
  lasen:['Wir % gestern ein Buch.','Die Kinder % laut vor.','Alle % still für sich.'],
  lagen:['Die Hefte % auf dem Tisch.','Wir % im Gras.','Zwei Steine % im Weg.'],
  'müssen':['Wir % jetzt gehen.','Alle % die Hände waschen.','Kinder % viel üben.'],
  mussten:['Wir % lange warten.','Alle % nach Hause.','Die Kinder % sich beeilen.'],
  rufen:['Wir % nach dem Hund.','Kannst du ihn bitte %?','Die Kinder % laut.'],
  riefen:['Wir % nach unserem Hund.','Alle % ihren Namen.','Die Kinder % um Hilfe.'],
  scheinen:['Die Sterne % hell.','Im Sommer % die Tage lang.','Die Lampen % durch das Fenster.'],
  schienen:['Gestern % die Sterne hell.','Alle % zufrieden zu sein.','Die Lichter % von weitem.'],
  schoben:['Wir % den Schrank zur Seite.','Alle % ihr Rad den Berg hoch.','Die Kinder % den Wagen.'],
  singen:['Wir % ein Lied.','Die Vögel % im Garten.','Kannst du laut %?'],
  sangen:['Wir % gestern im Chor.','Alle % das gleiche Lied.','Die Vögel % am Morgen.'],
  sitzen:['Wir % auf der Bank.','Die Vögel % im Baum.','Alle % ganz still.'],
  'saßen':['Wir % gestern im Garten.','Alle % um das Feuer.','Die Kinder % auf der Mauer.'],
  schlafen:['Wir % im Zelt.','Die Kinder % schon.','Katzen % sehr viel.'],
  schliefen:['Wir % im Zelt am See.','Alle % tief und fest.','Die Kinder % bis neun Uhr.'],
  schneiden:['Wir % das Papier klein.','Kannst du den Kuchen %?','Die Kinder % Sterne aus.'],
  schnitten:['Wir % das Papier in Streifen.','Alle % ihre Figuren aus.','Die Kinder % Sterne aus Papier.'],
  schreiben:['Wir % einen Brief an Oma.','Kannst du das bitte %?','Die Kinder % ihren Namen.'],
  schrieben:['Wir % gestern einen Brief.','Alle % ihren Namen darunter.','Die Kinder % eine Geschichte.'],
  stiegen:['Wir % auf den Turm.','Alle % in den Bus.','Die Kinder % aus dem Auto.'],
  schwammen:['Wir % gestern im See.','Die Enten % auf dem Teich.','Alle % bis zum Ufer.'],
  tragen:['Wir % die Taschen ins Haus.','Kannst du das bitte %?','Die Kinder % ihre Ranzen.'],
  trugen:['Wir % die Kisten hinauf.','Alle % feste Schuhe.','Die Kinder % ihre Ranzen selbst.'],
  trinken:['Wir % gern Apfelsaft.','Kinder sollen viel Wasser %.','Die Pferde % aus dem Eimer.'],
  tranken:['Wir % gestern Kakao.','Alle % kaltes Wasser.','Die Vögel % aus der Pfütze.'],
  'vergaßen':['Wir % das Heft zu Hause.','Alle % die Zeit.','Die Kinder % ihre Jacken.'],
  zogen:['Wir % den Schlitten den Hang hoch.','Die Pferde % den Wagen.','Alle % feste Schuhe an.'],

  /* --- Wörter, die oft kommen ---------------------------------------------- */
  ab:['Der Zug fährt gleich %.','Wir biegen links %.','Von morgen % sind Ferien.'],
  bin:['Ich % heute müde.','Morgen % ich acht Jahre alt.','Ich % gleich fertig.'],
  bis:['Wir bleiben % Montag.','Zähle % zehn.','Warte, % ich komme.'],
  bist:['Du % schon groß.','Wo % du gewesen?','Du % heute dran.'],
  dann:['Erst essen wir, % spielen wir.','Zuerst üben, % Pause.','Wir gehen % nach Hause.'],
  hier:['Wir wohnen schon lange %.','Das Buch bleibt %.','Ist % ein Platz frei?'],
  hin:['Wir fahren morgen %.','Leg es dort %.','Wo gehst du %?'],
  immer:['Sie kommt % zu spät.','Wir üben % am Abend.','Das ist % so gewesen.'],
  ins:['Wir gehen % Kino.','Sie springt % Wasser.','Leg das Heft % Regal.'],
  man:['In der Kirche muss % leise sein.','So etwas macht % einfach.','Von oben sieht % das Meer.'],
  nicht:['Das darfst du %.','Wir kommen heute %.','Der Hund beißt %.'],
  nichts:['Ich habe % gesagt.','Im Glas ist % mehr.','Sie wollte % davon wissen.'],
  nur:['Ich habe % ein Heft.','Wir bleiben % kurz.','Das war % ein Spaß.'],
  ob:['Ich frage, % sie kommt.','Weißt du, % es regnet?','Sag mir, % das stimmt.'],
  oft:['Wir gehen % zum Schwimmen.','Sie lacht ziemlich %.','Das passiert recht %.'],
  sehr:['Der Kuchen schmeckt % gut.','Sie freut sich %.','Das war % nett von dir.'],
  wann:['Sag mir, % du kommst.','Um % beginnt die Schule?','Weißt du, % Ferien sind?'],
  warum:['Sag mir, % du weinst.','Weißt du, % sie fehlt?','Ich frage mich %.'],
  wenig:['Im Glas ist noch % Saft.','Wir haben % Zeit.','Er redet ziemlich %.'],
  wie:['Sag mir, % das geht.','Er läuft schnell % der Wind.','Zeig mir, % du das machst.'],
  wieder:['Wir sehen uns bald %.','Sie ist % gesund.','Das Buch liegt % am Platz.'],
  zuletzt:['Wir räumen % auf.','Wer geht %?','Das habe ich % gesehen.'],

  /* --- Wörter mit ß --------------------------------------------------------- */
  'außer':['Alle kamen, % Lisa.','Wir haben % Milch nichts da.','Niemand war da, % ich.'],
  'draußen':['Die Kinder spielen %.','Es ist % sehr kalt.','Wir essen heute %.'],
  'heißen':['Wie % eure Hunde?','Die beiden % Max und Moritz.','Wir % alle gleich.'],
  'Straße':['Wir wohnen in dieser %.','Auf der % fahren Autos.','Pass beim Überqueren der % auf.'],

  /* --- Wörter zum Merken ----------------------------------------------------- */
  Christ:['Ein % feiert Weihnachten.','Er ist %, sie nicht.','Als % geht man in die Kirche.'],
  vielleicht:['Wir kommen % später.','Es regnet % morgen.','Sie hat % recht.'],
  vier:['Der Tisch hat % Beine.','Wir sind % Kinder.','Das Auto hat % Reifen.'],
  voll:['Das Glas ist ganz %.','Der Bus war sehr %.','Mein Ranzen ist %.'],
  Handy:['Mama telefoniert mit dem %.','Das % liegt auf dem Tisch.','Papa sucht sein %.'],
  Fuchs:['Im Wald lebt ein %.','Der % hat ein rotes Fell.','Ein % schleicht über die Wiese.'],
  links:['Wir biegen hier % ab.','Schau bitte nach %.','Das Haus steht % vom Weg.'],
  Taxi:['Am Bahnhof wartet ein %.','Das % hält vor dem Haus.','Sie ruft sich ein %.'],
  Text:['Lies den % bitte laut.','Im % stehen viele Wörter.','Wir schreiben einen kurzen %.'],
  sechs:['Wir stehen um % Uhr auf.','Die Klasse hat % Fenster.','Ich habe % Stifte.'],
  Pizza:['Heute essen wir %.','Die % kommt aus dem Ofen.','Er bestellt eine große %.'],
  Skizze:['Er zeichnet eine kleine %.','Die % zeigt den Weg.','Mach zuerst eine %.'],
  Stadt:['Wir wohnen in der %.','Die % hat einen großen Bahnhof.','In der % gibt es viele Läden.'],
  verwandt:['Wir sind miteinander %.','Sie ist mit mir %.','Die beiden sind nicht %.'],
  'erzählen':['Kannst du uns etwas %?','Die Kinder % von der Reise.','Oma kann gut %.'],
  fahren:['Wir % mit dem Bus.','Kannst du schon Rad %?','Die Autos % sehr schnell.'],
  wahr:['Diese Geschichte ist %.','Ist das wirklich %?','Kein Wort davon war %.'],
  zehn:['Ich zähle bis %.','Wir haben % Finger.','Der Bus kommt um % Uhr.'],
  Haar:['Ihr % ist sehr lang.','Ein % liegt auf dem Tisch.','Sein % ist ganz blond.'],
  Meer:['Im Sommer sind wir am %.','Das % ist heute ruhig.','Am % gibt es Muscheln.'],
  Schnee:['Im Winter liegt viel %.','Der % ist ganz weiß.','Wir spielen im %.'],
  See:['Wir baden im %.','Der % ist sehr tief.','Am % stehen viele Bäume.'],
  'Käfer':['Auf dem Blatt sitzt ein %.','Der % hat rote Punkte.','Ein kleiner % krabbelt davon.'],
  'Käfig':['Der Vogel sitzt im %.','Wir putzen den % aus.','Im % liegt frisches Stroh.'],
  'Märchen':['Oma liest uns ein % vor.','Dieses % kenne ich schon.','Im % gibt es eine Hexe.'],
  Tiger:['Im Zoo brüllt ein %.','Der % hat Streifen.','Ein % schläft im Schatten.'],
  Maschine:['Die % wäscht unsere Sachen.','Eine große % steht in der Halle.','Die % macht viel Lärm.'],
  Familie:['Meine % wohnt in Bayern.','Die ganze % kommt zusammen.','Zu meiner % gehört ein Hund.'],
  Laib:['Wir kaufen einen % Brot.','Der % liegt auf dem Brett.','Ein frischer % duftet gut.'],
};
